from models.actions import ActionType

# Polish labels for performed beekeeping actions (section "Wykonane działania").
ACTION_LABELS: dict[str, str] = {
    ActionType.feeding_syrup: "Podkarmianie syropem",
    ActionType.feeding_candy: "Podkarmianie ciastem (candy)",
    ActionType.feeding_pollen: "Podkarmianie pyłkiem / pierzgą",
    ActionType.feeding_water: "Pojenie wodą",
    ActionType.comb_added_drawn: "Dodano plaster odbudowany",
    ActionType.comb_added_foundation: "Dodano węzę",
    ActionType.comb_removed_old: "Usunięto stare plastry",
    ActionType.comb_removed_drone: "Wycięto czerw trutowy",
    ActionType.uncapping: "Odsklepianie",
    ActionType.super_added: "Dodano nadstawkę",
    ActionType.super_removed: "Zdjęto nadstawkę",
    ActionType.division_board_moved: "Przesunięto zatwór",
    ActionType.hive_expanded: "Poszerzono gniazdo",
    ActionType.honey_harvest: "Odbiór miodu (miodobranie)",
    ActionType.honey_frames_returned: "Zwrot ramek po miodobraniu",
    ActionType.queen_introduced: "Wprowadzono matkę",
    ActionType.queen_removed: "Usunięto matkę",
    ActionType.queen_cell_added: "Dodano matecznik",
    ActionType.queen_cells_removed: "Usunięto mateczniki",
    ActionType.swarm_caught: "Złapano rój",
    ActionType.split_made: "Wykonano odkład",
    ActionType.treatment_oxalic_acid: "Leczenie kwasem szczawiowym",
    ActionType.treatment_formic_acid: "Leczenie kwasem mrówkowym",
    ActionType.treatment_apistan: "Leczenie Apistan",
    ActionType.treatment_apivar: "Leczenie Apivar",
    ActionType.treatment_other_varroa: "Inne leczenie warrozy",
    ActionType.treatment_nosema: "Leczenie nosemozy",
    ActionType.treatment_other: "Inne leczenie",
    ActionType.hive_cleaned: "Czyszczenie ula / dennicy",
    ActionType.hive_moved: "Przeniesienie ula",
    ActionType.entrance_reduced: "Zwężenie wylotka",
    ActionType.entrance_opened: "Otwarcie wylotka",
    ActionType.mouse_guard_added: "Założono zabezpieczenie przed myszami",
    ActionType.mouse_guard_removed: "Zdjęto zabezpieczenie przed myszami",
    ActionType.insulation_added: "Dodano ocieplenie",
    ActionType.insulation_removed: "Usunięto ocieplenie",
    ActionType.other: "Inne",
}
