# WMO weather interpretation codes (as returned by Open-Meteo) -> Polish labels.
# https://open-meteo.com/en/docs#weathervariables
WEATHER_CODES: dict[int, str] = {
    0: "Bezchmurnie",
    1: "Głównie bezchmurnie",
    2: "Częściowe zachmurzenie",
    3: "Pochmurno",
    45: "Mgła",
    48: "Mgła osadzająca szron",
    51: "Mżawka słaba",
    53: "Mżawka umiarkowana",
    55: "Mżawka gęsta",
    56: "Marznąca mżawka słaba",
    57: "Marznąca mżawka gęsta",
    61: "Deszcz słaby",
    63: "Deszcz umiarkowany",
    65: "Deszcz silny",
    66: "Marznący deszcz słaby",
    67: "Marznący deszcz silny",
    71: "Śnieg słaby",
    73: "Śnieg umiarkowany",
    75: "Śnieg silny",
    77: "Ziarna śnieżne",
    80: "Przelotny deszcz słaby",
    81: "Przelotny deszcz umiarkowany",
    82: "Przelotny deszcz gwałtowny",
    85: "Przelotny śnieg słaby",
    86: "Przelotny śnieg silny",
    95: "Burza",
    96: "Burza z gradem słabym",
    99: "Burza z gradem silnym",
}
